name: employee_attendance
description: "Employee Attendance - Aplikasi Presensi Karyawan"
publish_to: 'none'

flutter_native_splash:
  color: "#ffffff"
  image: assets/apk.jpg

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  supabase_flutter: ^2.5.0
  crypto: ^3.0.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/apk.jpg
